name: Deployment pipeline

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
    types: ["opened", "synchronize"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run eslint

      - name: Build
        run: npm run build
      # - uses: rjstone/discord-webhook-notify@v1
      #   if: failure()
      #   with:
      #       severity: error
      #       details: Build failed at Pulkitxm/full-stack-open-pokedex deployed.
      #       webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test
        run: npm run test

      - name: E2E Test
        run: |
          npx playwright install --with-deps
          npx playwright test

      - name: Deploy
        # Only run this step if the branch is main
        if: ${{ (github.ref == 'refs/heads/master') && (github.event_name == 'push')}}
        env:
          deploy_url: https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        run: |
          curl "$deploy_url"

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tag commit
        if: ${{ (github.ref == 'refs/heads/master') && (github.event_name == 'push') && (!contains(join(toJSon(github.event.commits.*.message)), 'skip')) }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      # - uses: rjstone/discord-webhook-notify@v1
      #   if: success()
      #   with:
      #       severity: informational
      #       details:  A new version of Pulkitxm/full-stack-open-pokedex deployed.
      #       webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  # health_check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check the deployed service URL
  #       uses: jtalk/url-health-check-action@v3
  #       with:
  #         url: your_url
  #         follow-redirect: false
  #         max-attempts: 3
  #         retry-delay: 10s
  #         retry-all: false
