# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deployment pipeline

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master"]
    types: ["opened", "synchronize"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: E2E Test
        run: |
          npx playwright install --with-deps
          npx playwright test
      - name: Deploy
        # Only run this step if the branch is main
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name == 'push')}} 
        env:
          deploy_url: https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        run: |
          curl "$deploy_url"
